site_name: CKA Notes
repo_name: AlbinB97/CKA-Notes
repo_url: https://github.com/AlbinB97/CKA-Notes

nav:
  - Home: index.md
  - Commands:
    - Imperative: commands/imperative.md
    - Network: commands/network.md

plugins:
  - search

theme:
  name: material
  logo: img/CKA-img.png
  favicon: img/favicon.ico
