site_name: CKA Notes
repo_name: AlbinB97/CKA-Notes
repo_url: https://github.com/AlbinB97/CKA-Notes

nav:
  - Home: index.md
  - Commands: commands.md

theme:
  name: dracula
  logo: img/CKA-img.png
  favicon: img/favicon.ico

plugins:
  - search