site_name: CKA Notes
repo_name: AlbinB97/CKA-Notes
repo_url: https://github.com/AlbinB97/CKA-Notes

nav:
  - Home: index.md
  - Commands:
    - WIP: commands/WIP.md
    - Imperative: commands/imperative.md
    - Network: commands/network.md
    - Crictl: commands/crictl.md
  - Information:
    - Etcd FAQ: information/etcd.md
    - Diagnose Crashed Apiserver: information/diagnose-crashed-apiserver.md
    - YAML FAQ: information/yaml-faq.md
    - Vi 101: information/vi-101.md

plugins:
  - search

theme:
  name: material
  logo: img/CKA-img.png
  favicon: img/favicon.ico
